### ISSUE TITLE
fetch_database doesn't work with TUH format

### ISSUE THREAD

**Issue by fernandokm** [Aura-healthcare/seizure_detection_pipeline#7]
There are some places where the script [fetch_database.py](src/usecase/fetch_database.py) is hardcoded to use the teppe format instead of tuh. We can fix this locally for now by adding the following to the script:
```py
TEPPE_PATIENT_PATTERN = TUH_PATIENT_PATTERN
DB = 'tuh'
```
but that is just a temporary fix. It seems like the script was intended to support both formats, so there should be a better way of fixing this problem.

**Comment by alexisgcomte** [comment]
Issue is now solved
